services:
  test-db:
    image: postgres:17.5-alpine
    container_name: su_backend_test_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=su_test_db
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    restart: always