FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

COPY .mvn .mvn
COPY mvnw .
COPY pom.xml .

COPY src ./src

EXPOSE 8080

ENV MAVEN_OPTS=-Xmx1024m

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]
