package pl.su.su_backend.model.enums;

public enum ActionType {

    REGISTER,
    UPDATE_PROFILE,
    SOFT_DELETE,

    // ROLES
    ASSIGN_ROLE,
    REMOVE_ROLE,
    PERMISSION_UPDATE,

    // USER ADMIN ACTIONS
    USER_UNBLOCKED,
    USER_UPDATED,

    COUNCIL_CREATE,

    // EVENTS
    EVENT_CREATE,
    EVENT_DELETE,
    EVENT_LEAVE,
    EVENT_APPROVE,
    EVENT_REJECT,


    // SUGGESTIONS
    SUGGESTION_CREATE,
    SUGGESTION_UPDATE,
    SUGGESTION_APPROVE,
    SUGGESTION_REJECT,
    SUGGESTION_DELETE,

    // BUDGET
    BUDGET_CREATE,
    BUDGET_UPDATE,
    BUDGET_DELETE,
    TRANSACTION_CREATE,
    TRANSACTION_EDIT,
    TRANSACTION_DELETE
}
